sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.3
  - 2.5.5
env:
  - DRIVER=chrome
  - DRIVER=firefox
addons:
  sauce_connect: true
branches:
  only:
    - master
before_install:
  - cp -f travis/database.yml config/
  - bundler update --bundler
script:
  - bundle exec rake dad:db:create DAD_MYSQL_NO_ROOT_PASSWORD=true
  - bin/rails db:schema:load
  - bin/rails test
  - bundle exec rake dad:test
