sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.2
  - 2.2.6
  - 2.1.9
before_script:
  - cp -f travis/database.yml config/
  - bundle exec rake dad:db:create DAD_MYSQL_NO_ROOT_PASSWORD=true
  - bundle exec rake db:schema:load
script:
  - bundle exec rake test
  - bundle exec rake dad:test CI=travis

