sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
env:
  - DRIVER=chrome
  - DRIVER=firefox
addons:
  sauce_connect: true
before_script:
  - cp -f travis/database.yml config/
  - bundle exec rake dad:db:create DAD_MYSQL_NO_ROOT_PASSWORD=true
  - bin/rails db:schema:load
script:
  - bin/rails test
  - bundle exec rake dad:test

