sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.2
  - 2.3.5
before_script:
  - cp -f travis/database.yml config/
  - bundle exec rake dad:db:create DAD_MYSQL_NO_ROOT_PASSWORD=true
  - bundle exec rake db:schema:load
script:
  - bin/rails test
  - bundle exec rake dad:test

