sudo: false
language: ruby
rvm:
  - 2.7.3
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
env:
  - PLATFORM=Linux DRIVER=chrome
  - PLATFORM="Windows 10" DRIVER=chrome
services:
  - mysql
addons:
  sauce_connect: true
branches:
  only:
    - master
before_install:
  - cp -f travis/database.yml config/
  - gem update --system
  - gem install bundler
install:
  - bundle install --jobs 3 --retry 3
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn
script:
  - bundle exec rake dad:db:create DAD_MYSQL_NO_ROOT_PASSWORD=true
  - bin/rails db:schema:load
  - bin/rails test
  - bundle exec rake dad:test
