ARG registry
FROM ${registry}/bookmarks/base:latest

RUN sudo yum -y install mariadb-devel

ENV RAILS_ENV=test

ADD  config ./config
RUN sudo chown -R ${USER}:${USER} ./
RUN bundle exec rake dad:setup:test
