ARG registry
FROM ${registry}/hybitz-almalinux:8.10-20251124-52

ADD Gemfile Gemfile.lock ./
RUN sudo chown -R ${USER}:${USER} ./ && \
    bundle config without 'itamae development test' && \
    bundle install -j2

ADD Rakefile ./
ADD config ./config
RUN sudo chown -R ${USER}:${USER} ./ && \
    bundle exec rake dad:setup:base RAILS_ENV=production SECRET_KEY_BASE=dummy
