FROM ${registry}/hybitz-centos:7.9.2009

ADD Gemfile Gemfile.lock Rakefile ./
RUN sudo chown -R ${USER}:${USER} ./
RUN bundle install -j2

ADD package.json yarn.lock ./
RUN sudo chown -R ${USER}:${USER} ./
RUN yarn install
