ARG registry
FROM ${registry}/hybitz-centos:7.9.2009

ADD Gemfile Gemfile.lock Rakefile ./
RUN sudo chown -R ${USER}:${USER} ./ && \
    bundle install -j2

ADD package.json yarn.lock ./
RUN sudo chown -R ${USER}:${USER} ./ && \
    yarn install && \
    yarn cache clean
