ARG registry
FROM ${registry}/bookmarks/base:latest

ENV CI=jenkins
ENV RAILS_ENV=test

ADD Rakefile ./
ADD config ./config
RUN sudo chown -R ${USER}:${USER} ./ && \
    bundle exec rake dad:setup:test
