apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmarks-app
  labels:
    app: bookmarks-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmarks-app
  template:
    metadata:
      labels:
        app: bookmarks-app
    spec:
      restartPolicy: Always
      containers:
      - name: bookmarks
        image: bookmarks/app:latest
        envFrom:
        - configMapRef:
            name: bookmarks-config
        - secretRef:
            name: bookmarks-secret
        command: ['bundle', 'exec', 'rails', 's']
