# shared:
#   api_key: a1B2c3D4e5F6

default: &default
  otp_length: 4
  omniauth_google_oauth2_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  omniauth_google_oauth2_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  omniauth_google_api_key: <%= ENV['GOOGLE_API_KEY'] %>
  omniauth_twitter_client_id: <%= ENV["TWITTER_CLIENT_ID"] %>
  omniauth_twitter_client_secret: <%= ENV["TWITTER_CLIENT_SECRET"] %>

development:
  <<: *default
  secret_key_base: 648bf58d02ebe90e63cf5d1ceea8f1947f27bfc7e1c56899ef0137e07a77b8915a0a7a36361d4f037df7e7874423bd7d00e24b5f8c9d20de1126640296882ffb

test:
  <<: *default
  secret_key_base: 1d3456b00932cab86d1890c951aad802d6476d34759aa2c0fecab43975afcae0b3efb0826a40bc45bd6a1e980a27c79e662a7e645573303cae2d7d6759b648eb

production:
  <<: *default
  otp_length: <%= ENV["BOOKMARKS_OTP_LENGTH"] || 6 %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || '32c2ed974a47aff7f4816ba3804809e1b50e44daa4fae886dfc8f572787a68410e1305a1984ae9d340b813eca1777b7a679ce6deb7d9f68b65e9cbb36ed40a1c' %>
  default_url_options:
    protocol: https
    host: <%= ENV['HOST'] || 'localhost' %>
  smtp_settings:
    address: <%= ENV['AWS_ADDRESS'] %>
    port: 587
    domain: <%= ENV['AWS_DOMAIN'] %>
    authentication: login
    user_name: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    password: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
