apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name bookmarks-app
  labels: &labels
    app: *name
spec:
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      restartPolicy: Always
      containers:
      - name: *name
        image: bookmarks/app:latest
        envFrom:
        - configMapRef:
            name: bookmarks-config
        - secretRef:
            name: bookmarks-secret
        env:
        command: ["/usr/local/bin/bundle"]
        args: ["exec", "rails", "s"]
