resources:
- app.yml
- db.yml
- service.yml

generatorOptions:
  immutable: true
configMapGenerator:
- name: bookmarks-config
  literals:
  - PORT=3000
  - RAILS_LOG_TO_STDOUT=true
  - RAILS_SERVE_STATIC_FILES=true
